export enum LocalModelErrorCode {
    NODE_LLAMA_NOT_INSTALLED = 'LOCAL_001',
    
    NODE_LLAMA_INSTALL_FAILED = 'LOCAL_002',
    
    CMAKE_NOT_FOUND = 'LOCAL_003',
    
    BUILD_FAILED = 'LOCAL_004',

    DOWNLOAD_FAILED = 'LOCAL_010',
    
    DOWNLOAD_INTERRUPTED = 'LOCAL_011',
    
    DOWNLOAD_HASH_MISMATCH = 'LOCAL_012',
    
    INSUFFICIENT_DISK_SPACE = 'LOCAL_013',
    
    HF_AUTH_REQUIRED = 'LOCAL_014',
    
    NETWORK_ERROR = 'LOCAL_015',

    MODEL_NOT_FOUND = 'LOCAL_020',
    
    MODEL_NOT_DOWNLOADED = 'LOCAL_021',
    
    MODEL_LOAD_FAILED = 'LOCAL_022',
    
    MODEL_CORRUPT = 'LOCAL_023',
    
    INVALID_GGUF = 'LOCAL_024',
    
    CONTEXT_TOO_LARGE = 'LOCAL_025',

    GPU_NOT_AVAILABLE = 'LOCAL_030',
    
    INSUFFICIENT_VRAM = 'LOCAL_031',
    
    GPU_DRIVER_ERROR = 'LOCAL_032',
    
    METAL_NOT_AVAILABLE = 'LOCAL_033',
    
    CUDA_NOT_AVAILABLE = 'LOCAL_034',
    
    VULKAN_NOT_AVAILABLE = 'LOCAL_035',

    OLLAMA_NOT_RUNNING = 'LOCAL_040',
    
    OLLAMA_MODEL_NOT_FOUND = 'LOCAL_041',
    
    OLLAMA_PULL_FAILED = 'LOCAL_042',
    
    OLLAMA_API_ERROR = 'LOCAL_043',
    
    OLLAMA_VERSION_INCOMPATIBLE = 'LOCAL_044',
}
