
export enum StorageErrorCode {
    MANAGER_NOT_INITIALIZED = 'storage_manager_not_initialized',
    MANAGER_NOT_CONNECTED = 'storage_manager_not_connected',
    DEPENDENCY_NOT_INSTALLED = 'storage_dependency_not_installed',
    CONNECTION_FAILED = 'storage_connection_failed',
    CONNECTION_CONFIG_MISSING = 'storage_connection_config_missing',
    READ_FAILED = 'storage_read_failed',
    WRITE_FAILED = 'storage_write_failed',
    DELETE_FAILED = 'storage_delete_failed',
    MIGRATION_FAILED = 'storage_migration_failed',
    DATABASE_INVALID_CONFIG = 'storage_database_invalid_config',
    CACHE_INVALID_CONFIG = 'storage_cache_invalid_config',
    BLOB_INVALID_CONFIG = 'BLOB_INVALID_CONFIG',
    BLOB_SIZE_EXCEEDED = 'BLOB_SIZE_EXCEEDED',
    BLOB_TOTAL_SIZE_EXCEEDED = 'BLOB_TOTAL_SIZE_EXCEEDED',
    BLOB_INVALID_INPUT = 'BLOB_INVALID_INPUT',
    BLOB_ENCODING_ERROR = 'BLOB_ENCODING_ERROR',
    BLOB_NOT_FOUND = 'BLOB_NOT_FOUND',
    BLOB_INVALID_REFERENCE = 'BLOB_INVALID_REFERENCE',
    BLOB_ACCESS_DENIED = 'BLOB_ACCESS_DENIED',
    BLOB_CORRUPTED = 'BLOB_CORRUPTED',
    BLOB_BACKEND_NOT_CONNECTED = 'BLOB_BACKEND_NOT_CONNECTED',
    BLOB_BACKEND_UNAVAILABLE = 'BLOB_BACKEND_UNAVAILABLE',
    BLOB_CLEANUP_FAILED = 'BLOB_CLEANUP_FAILED',
    BLOB_OPERATION_FAILED = 'BLOB_OPERATION_FAILED',
}
