export enum HookErrorCode {
    HOOK_LOAD_FAILED = 'HOOK_LOAD_FAILED',
    HOOK_INVALID_SHAPE = 'HOOK_INVALID_SHAPE',
    HOOK_INSTANTIATION_FAILED = 'HOOK_INSTANTIATION_FAILED',
    HOOK_INITIALIZATION_FAILED = 'HOOK_INITIALIZATION_FAILED',
    HOOK_CONFIGURATION_INVALID = 'HOOK_CONFIGURATION_INVALID',
    HOOK_EXECUTION_FAILED = 'HOOK_EXECUTION_FAILED',
    HOOK_EXECUTION_TIMEOUT = 'HOOK_EXECUTION_TIMEOUT',
    HOOK_BLOCKED_EXECUTION = 'HOOK_BLOCKED_EXECUTION',
    HOOK_DUPLICATE_PRIORITY = 'HOOK_DUPLICATE_PRIORITY',
    HOOK_DEPENDENCY_NOT_INSTALLED = 'HOOK_DEPENDENCY_NOT_INSTALLED',
    HOOK_PROVIDER_ALREADY_REGISTERED = 'HOOK_PROVIDER_ALREADY_REGISTERED',
    HOOK_PROVIDER_NOT_FOUND = 'HOOK_PROVIDER_NOT_FOUND',
    HOOK_PROVIDER_VALIDATION_FAILED = 'HOOK_PROVIDER_VALIDATION_FAILED',
}

export type { HookErrorCode as default };
